apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: projectsveltos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: docker.io/projectsveltos/dashboard:v0.46.1
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: projectsveltos
spec:
  selector:
    app: dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP
