export const API_ENDPOINTS = {
  RESOURCES: "/resources",
  HELM_CHART: "/helmcharts",
  PROFILE_STATUSES: "/getClusterStatus",
  CAPI_CLUSTERS: "/capiclusters",
  SVELTOS_CLUSTERS: "/sveltosclusters",
  PROFILES: "/profiles",
  PROFILE: "/profile",
  DRY_RUN_CHANGES: "/dryRunChanges",
  MCP_INSTALLATION: "/installation",
  MCP_CLUSTER_DEBUG: "/debugCluster",
  MCP_PROFILE_CLUSTER_DEBUG: "/debugProfileCluster",
  MCP_EVENT_PIPELINE_DEBUG: "/analyzeEventPipeline",
  MCP_CLASSIFIER_PIPELINE_DEBUG: "/analyzeClassifierPipeline",
  EVENTS: "/events",
  EVENT: "/event",
  CLASSIFIERS: "/classifiers",
  CLASSIFIER: "/classifier",
  STATS: "/stats",
};
